-- Q11. Revenue generated by each pizza.
SELECT pizza_type_id, SUM(price) FROM pizzas
GROUP BY pizza_type_id;
-- Q12. Total revenue.
SELECT SUM(price) AS Total_revenue FROM pizzas;
-- Q13.revenue by category.
SELECT pizza_types.category, SUM(pizzas.price) AS Revenue  FROM pizzas JOIN pizza_types
ON pizza_types.pizza_type_id = pizzas.pizza_type_id
GROUP BY pizza_types.category;
-- Q14. Peak ordering hours.
SELECT EXTRACT(HOUR FROM time_) AS HOUR_, COUNT(order_id) FROM orders
GROUP BY EXTRACT(HOUR FROM time_)
ORDER BY EXTRACT(HOUR FROM time_);
-- Q15. Average price by pizza size.
SELECT pizza_id , AVG(price) AS avg_price FROM pizzas
GROUP BY pizza_id
ORDER BY pizza_id;
-- Q16. Find the category with the highest total quantity sold.
SELECT   pt.category, SUM(od.quantity) AS total_qty FROM order_details od
JOIN pizzas p  
ON od.pizza_id = p.pizza_id
JOIN pizza_types pt 
ON p.pizza_type_id  = pt.pizza_type_id
GROUP BY pt.category
ORDER BY total_qty DESC
LIMIT    1;
-- Q17. Find pizzas that were never ordered.
SELECT
    p.pizza_id,
    p.size_,
    p.price
FROM pizzas p
LEFT JOIN order_details od ON p.pizza_id = od.pizza_id
WHERE od.pizza_id IS NULL;

-- Q18. Find all orders where total quantity is greater than 3.
SELECT
    order_id,
    SUM(quantity) AS total_qty
FROM order_details
GROUP BY order_id
HAVING SUM(quantity) > 3;

-- Q19. Find which pizza size generates the highest revenue.
SELECT
    p.size_,
    SUM(p.price * od.quantity) AS revenue
FROM pizzas p
JOIN order_details od ON p.pizza_id = od.pizza_id
GROUP BY p.size_
ORDER BY revenue DESC
LIMIT 1;

-- Q20. Find orders where quantity is greater than average quantity.
SELECT
    order_details_id,
    order_id,
    pizza_id,
    quantity
FROM order_details
WHERE quantity > (
    SELECT AVG(quantity)
    FROM order_details
);